package com.java.boot.puffin_resume_bot.flow;

public enum ResumeState {
    ASK_FULLNAME,
    ASK_PHOTO,
    ASK_PHONE,
    ASK_EMAIL,
    ASK_TELEGRAM,
    ASK_GITHUB,
    ASK_LINKEDIN,
    ASK_POSITION,
    ASK_ABOUT,
	ASK_PROJECT_URL,
	ASK_PROJECT_TECHS,
	ASK_WORK_POSITION,
	ASK_WORK_COMPANY,
	ASK_WORK_PERIOD,
	ASK_WORK_DUTY,
	ASK_WORK_MORE,
	ASK_EDU_UNIVERSITY,  
	ASK_EDU_FACULTY,     
	ASK_EDU_PERIOD,     
	ASK_EDU_MORE,
	ASK_LOCATION,
	CONFIRM_LOCATION,
	ASK_TECH_SKILLS,
	ASK_SOFT_SKILLS,
    ASK_LANG_NAME,
    ASK_LANG_LEVEL,
	ASK_HOBBIES,

    READY
}
